#note to self as of Friday, May 17, 2024, 12:44:16, having scale anything other than 1 results in X11 apps being blurry/pixelated

### MAIN LAPTOP MONITOR ###
	#monitor = eDP-1, preferred, 0x0, auto #MAIN MONITOR (LAPTOP SCREEN)
	#monitor = eDP-1, preferred, 0x0, 1.3
	#monitor = eDP-1, preferred, 0x0, 1.2
	monitor = eDP-1, preferred, 0x0, 1
	#monitor = eDP-1, preferred, 0x0, 1 #as of Thursday, September 19, 2024, 10:01:07, might go with this to give my waybar some more room...

### SECONDARY MONITOR ###
	$SECONDARYMONITOR=HDMI-A-1
	#monitor = $SECONDARYMONITOR, preferred, auto, 1, mirror, eDP-1
	#monitor = $SECONDARYMONITOR, preferred, auto, 1.2
	#monitor = $SECONDARYMONITOR, preferred, auto-right, 1.5
	#monitor = $SECONDARYMONITOR, preferred, auto, 1
	monitor = $SECONDARYMONITOR, preferred, auto, 1

	#auto-up, auto-down, auto-left, auto-right
		#pro-tip as of Wednesday, May 29, 2024, 01:12:49:
			#get monitor dimensions, divide X and Y by scale, use new dimensions minus one to position monitors
			#eg:
				#1920x1080 but in scale 1.2, so 1920/1.2 = 1600, 1080/1.2 = 900, so we would do:
				#"monitor = $SECONDARYMONITOR, preferred, 1599x0, 1" in order to have to right of monitor 1

#monitor=,preferred,auto,1
#^^ for plugging in random monitors

# See https://wiki.hyprland.org/Configuring/Monitors/
#EXAMPLES:
	#monitor = name, resolution, position, scale

	#monitor=DP-1,1920x1080@144,0x0,1
		#This will make the monitor on DP-1 a 1920x1080 display, at 144Hz, 0x0 off from the top left corner, with a scale of 1 (unscaled).

	#"hyprctl monitors all"
	
		#You can use "preferred" as a resolution to use the display’s preferred size,
		#or you can use "highres" or "highrr" to get the best possible resolution or refresh rate for your monitor.
	
	#monitor = DP-1, modeline 1071.101 3840 3848 3880 3920 2160 2263 2271 2277 +hsync -vsync, 0x0, 1
	#monitor = DP-1, modeline 1071.101 3840 3848 3880 3920 2160 2263 2271 2277 +hsync -vsync, 0x0, 1

	#monitor=name,addreserved,TOP,BOTTOM,LEFT,RIGHT
	
	#monitor=DP-3,1920x1080@60,0x0,1,mirror,DP-2
	#monitor=,preferred,auto,1,mirror,DP-1

	#monitor=eDP-1,2880x1800@90,0x0,1,bitdepth,10
	
	#TRANSFORMATIONS SCREEN ROTATION ROTATE
		#monitor=eDP-1,2880x1800@90,0x0,1,transform,1

		#normal (no transforms) -> 0
		#90 degrees -> 1
		#180 degrees -> 2
		#270 degrees -> 3
		#flipped -> 4
		#flipped + 90 degrees -> 5
		#flipped + 180 degrees -> 6
		#flipped + 270 degrees -> 7
