#"https://wiki.hyprland.org/Configuring/Workspace-Rules/"

### MAIN LAPTOP MONITOR "eDP-1" ###
	workspace=1,monitor:eDP-1,persistent:true,defaultName:1,default:true
	workspace=2,monitor:eDP-1,persistent:true,defaultName:2
	workspace=3,monitor:eDP-1,persistent:true,defaultName:3
	workspace=4,monitor:eDP-1,persistent:true,defaultName:4

### SECONDARY MONITOR "HDMI-A-1" ###
	$SECONDARYMONITOR=HDMI-A-1
	workspace=5,monitor:$SECONDARYMONITOR,persistent:true,defaultName:5,default:true
	workspace=6,monitor:$SECONDARYMONITOR,persistent:true,defaultName:6
	workspace=7,monitor:$SECONDARYMONITOR,persistent:true,defaultName:7
	workspace=8,monitor:$SECONDARYMONITOR,persistent:true,defaultName:8
